name: infrastructure-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  infrastructure-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infrastructure

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Infrastructure Init
        run: tofu init

      - name: Infrastructure Plan
        run: tofu plan

      - name: Infrastructure Apply
        if: github.event_name == 'workflow_dispatch'
        run: tofu apply -auto-approve
